[build]
  command = "npm run build"
  functions = "functions"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run serve"
  targetPort = 6000
  port = 6001
  publish  = "dist"
  autoLaunch = false